### ISSUE TITLE
Failure running “Compile & Run”

### ISSUE THREAD

**Issue by WarFox** [textmate/java.tmbundle#25]
I am getting this error when trying to run Java program in Textmate with ⌘ + R combination.

/Users/{user}/Library/Application Support/TextMate/Managed/Bundles/Java.tmbundle/Support/bin/javamate.rb:3: undefined method `+' for nil:NilClass (NoMethodError)

I am new to Textmate and have no clue how to solve this.

My Java Version details is:

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
```

**Comment by prakask** [comment]
I was getting error using Textmate 2.0.19 using HighSierra  related to unable to install Ruby 1.8 when ever I try to compile java(for example). If you know the ruby is already installed the simplest option is to create a softlink ruby18 to for ruby.
sudo ln -s /usr/bin/ruby /usr/bin/ruby18
