### ISSUE TITLE
Formating Problems with < in block-comments

### ISSUE THREAD

**Issue by itshorty** [textmate/java.tmbundle#32]
Hi,

the Java highlighter has a problem formating block-comments containing '<'

For an example see here (starting at Line 220): https://github.com/itshorty/libsybos/blob/master/src/main/java/at/ffesternberg/sybos/SybosClient.java#L220

greetings Florian

**Comment by infininight** [comment]
Fixed in textmate/javadoc.tmbundle@5276d7a93f0cf53b7d425c39c6968b09ea9f2d40, thanks for the report.
