### ISSUE TITLE
Java enums and annotations

### ISSUE THREAD

**Issue by ming13** [textmate/java.tmbundle#35]
It seems like the highlighting of Java `enum` types with annotations set is a little bit off. [Example](https://github.com/hawkular/hawkular-android-client/blob/d0df3e2b225b21437649b3d6c2067c6ffb6c8613/src/main/java/org/hawkular/client/android/backend/model/AlertType.java#L25-L27).

GitHub uses this bundle to provide syntax highlighting for Java source code. Original issue is github/linguist#2473.

**Comment by pchaigno** [comment]
@infininight Did you get a chance to look into this?

**Comment by infininight** [comment]
@pchaigno The issue can be pinpointed to not supporting the usage of `@SerializedName("THRESHOLD")`, it is not expecting that to appear in a list of enums. I could patch around the issue but I'd rather have someone more familiar with the Java language provide a proper fix or at least a good description of the issue.

**Comment by ming13** [comment]
I think the issue here is related to a possible fact that the syntax doesn’t know that `enum` fields can have annotations. From the syntax itself it seems like it tries to highlight everything after the first field to `;` as field. The rest of highlighting goes fine—you can take a look at [the updated class](https://github.com/hawkular/hawkular-android-client/blob/34707c17d84bc49eb1c8f53b4ffad4122aab9e4b/src/main/java/org/hawkular/client/android/backend/model/AlertType.java).
