### ISSUE TITLE
Add highlight support for "module-info.java"

### ISSUE THREAD

**Issue by rn4n** [textmate/java.tmbundle#47]
[module-info][1] is a new source file used on Java projects for module declaration. It will be released on jdk9 ([7/17/2017][2]) as part of [project Jigsaw][3]. For now, the file does not have hightlight support as you can see [here][5].

I don't know about this file yet, but reading [the specification][4]:

> **`open`, `module`, `requires`, `transitive`, `exports`, `opens`, `to`, `uses`, `provides`, and `with` are restricted keywords** (...)

> (...) **A module name consists of one or more Java identifiers separated by "." tokens**. In the declaration of a module name (after module) and in any use of a module name (by requires, exports, or opens), every identifier in the name must end with a Java letter, or a compile-time error occurs.

Annotations and `static`/`transitive` modifiers are allowed too.

This information is sufficient to add support for this file? 

I opened an issue in the repository of the [linguist][6] ([#3566][7]), but they asked me to open the issue in this repository.

_- cheers._

[1]:https://github.com/reebr/playground/blob/master/java/jigsaw-calculator/src/calculator/classes/module-info.java
[2]:http://www.java9countdown.xyz/
[3]:http://openjdk.java.net/projects/jigsaw/quick-start
[4]:http://cr.openjdk.java.net/~mr/jigsaw/spec/lang-vm.html#jigsaw-1.1
[5]:https://github.com/search?utf8=%E2%9C%93&q=module-info+extension%3Ajava&type=Code&ref=advsearch&l=&l=

[6]:https://github.com/github/linguist
[7]:https://github.com/github/linguist/issues/3566

**Comment by reebr** [comment]
@alkemist, @sorbits, @infininight, @blalor, @bradleyjames, @bnmnetp.

Is this repository still active?

**Comment by blalor** [comment]
I've been using Sublime Text for years, now.  Sorry.

**Comment by michihausheer** [comment]
As this is used by https://github.com/github/linguist/, it would be great if someone could implement it.
