### ISSUE TITLE
TextMate fails to find javac and java

### ISSUE THREAD

**Issue by McPringle** [textmate/java.tmbundle#51]
**Steps to reproduce**
1. Install Java 8 using [SDKMAN](http://sdkman.io/)
2. Set `JAVA_HOME` environment variable pointing to the JDK installation
3. Add `$JAVA_HOME/bin` to the `PATH` environment variable
4. Start TextMate, create a File named `Sample.java` and hit `Compile & Run` hotkey

**The Java file**
```java
public class Sample {
    public static void main(String[] args) {
        System.out.println("Hello, TextMate!");
    }
}
```

**Expected Result**
1. The Java file gets compiled without errors
2. The output shoud be `Hello, TextMate`

**Actual Result**
1. Error message: `No Java runtime present, requesting install.`
2. Dialog box from the OS shows up to install Java

**Environment**
- macOS High Sierra 10.13.3
- TextMate 2.0-rc.4
- openJDK 1.8.0_152

In my opinion, this bundle should use the `javac` and `java` command from the installation the `JAVA_HOME` environment variable points to and use `/usr/bin/javac` and `/usr/bin/java` only as a fallback.

A small modification of `java_compile_and_run.sh` should fix this, I guess.

**Comment by infininight** [comment]
We use the variable TM_JAVA for this purpose. Unfamiliar with SDKMAN, is this a common installation method for java?

**Comment by McPringle** [comment]
Most software developers I know who own a Mac are using SDKMAN to manage their toolchain. It is extremely popular. Anyway, this issue is not SDKMAN specific.

As @infininight suggested I set `TM_JAVA` to point to the installed JDK:

```export TM_JAVA=${JAVA_HOME}```

With no effect to TM, I still got the same error message: `No Java runtime present, requesting install.`

I checked the variable was set successfully in the terminal and started TM from the same terminal.

Any more suggestions?

**Comment by McPringle** [comment]
Thanks to the #textmate IRC chat I figured it out. To help other new users of TextMate, I added a hint to the README file of this bundle.

**Comment by sorbits** [comment]
> I experienced the same problem. So where is this README file supposed to help us ? Thanks.

It refers to this: https://github.com/textmate/java.tmbundle/pull/52/commits/dd6b26a41b0de885c1d17ddabf6bd082f3f37c0a

We haven’t merged it yet because we haven’t gotten around to verifying the instructions, sorry.

/cc @infininight
